name: Sentry release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to release to Sentry'
        required: false
        default: ''

  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Sentry version
        id: set-version
        run: |
          if [ "${{ github.event.inputs.version }}" != "" ]; then
            # Remove 'v' prefix if present in the input version
            VERSION="${{ github.event.inputs.version }}"
            VERSION="${VERSION#v}"
            echo "version=$VERSION" >> $GITHUB_ENV
          else
            echo "version=$(echo ${{ github.ref }} | grep -oP '(?<=refs/tags/v).*')" >> $GITHUB_ENV
          fi

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          # SENTRY_URL: https://sentry.io/
        with:
          environment: production
          version: ${{ env.version }}